# Site settings
baseURL = "//wckanal.sk/"
languageCode = "sk"
title = "Krtkovanie, odpady - Šimurda"
theme = "hugo-split-theme"
disableKinds = ["section", "taxonomy", "taxonomyTerm", "RSS", "sitemap"]

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Copyright
copyright = "&copy;2019 Šimurda"

[params]

  # Metadata for search engines and social sharing
  author = "Jarko Šimurda"
  description = "TV monitoring potrubia a čistenie"
  #shareImage = "images/social.jpg"
  #twitterHandle = "onepagelove"

  # Favicon
#  favicon = "favicon.ico"

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "images/profilephoto.png"
      position = "center center"

#    # Video
#    [params.visual.video]
#      enable = false
#      mute = true
#      file = "videos/background.mp4"
#      # youtubeId = "dk9uNWPP7EA"

  # Links
  #
  # Links List #1
  [[params.links]]
    [params.links.list1]
      heading = "Kontakt"

      [[params.links.list1.link]]
        text = "904 693 711"
        url = "tel:+421904693711"

      [[params.links.list1.link]]
        text = "simurda@wckanal.sk"
        url = "mailto:simurda@wckanal.sk"


  # Links List #2
  [[params.links]]
    [params.links.list2]
      heading = "Social"

      [[params.links.list2.link]]
        text = "Instagram"
        url = "#"



  # The original template is released under the Creative Commons Attribution 3.0 License.
  # Please keep the original attribution link when using for your own project.
  # If you'd like to use the template without the attribution, you can check out
  # the license option via the template author's website: https://onepagelove.com/split
